name: Integration reusable workflow
on:
  workflow_call:
    inputs:
      SCRIPT:
        required: true
        type: string
    secrets:
      INTEGRATION_INSTANCE_KEYS:
        required: true
      MAILSAC_API_KEY:
        required: true

jobs:
  run:
    continue-on-error: true
    timeout-minutes: 60
    runs-on: ${{ vars.RUNNER_NORMAL }}
    concurrency:
      group: integration-${{ github.ref }}-${{ inputs.script }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log($(npm ls @playwright/test --json).dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Download Verdaccio artifacts
        uses: actions/download-artifact@v3
        with:
          name: verdaccio
          path: .verdaccio
      - name: Run Verdaccio
        run: |
          npm set registry http://localhost:4873/
          nohup ./node_modules/.bin/verdaccio --config ./verdaccio.install.yaml &
          sleep 5
      - name: Install @clerk/backend in /integration
        run: |
          cd integration && npm init -y && npm install @clerk/backend && cd ..
      - name: Run Playwright tests
        run: ${{ inputs.SCRIPT }}
        env:
          INTEGRATION_INSTANCE_KEYS: ${{ secrets.INTEGRATION_INSTANCE_KEYS }}
          MAILSAC_API_KEY: ${{ secrets.MAILSAC_API_KEY }}
          E2E_CLERK_VERSION: 'latest'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
