name: 'Lock stale PRs and issues'

on:
  workflow_dispatch:
  schedule:
    # This runs 4 times a day:
    # https://crontab.guru/#0_0,12_*_*_*
    - cron: '0 0,6,12,18 * * *'

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ${{ vars.RUNNER_NORMAL }}
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.CLERK_COOKIE_PAT }}
          days-before-issue-stale: 30
          days-before-pr-stale: 50
          days-before-issue-close: 10
          days-before-pr-close: 10
          exempt-all-assignees: true
          exempt-issue-labels: 'needs-triage,prioritized,feature-request'
          stale-issue-message: |
            Hello ğŸ‘‹

            We currently close issues after 40 days of inactivity. It's been 30 days since the last update here. If we missed this issue, please reply here. Otherwise, we'll close this issue in 10 days.

            As a friendly reminder: The best way to see an issue fixed is to open a pull request. If you're not sure how to do that, please check out our [contributing guide](https://github.com/clerk/javascript/blob/main/docs/CONTRIBUTING.md).

            Thanks for being a part of the Clerk community! ğŸ™
          stale-pr-message: |
            Hello ğŸ‘‹

            We currently close PRs after 60 days of inactivity. It's been 50 days since the last update here. If we missed this PR, please reply here. Otherwise, we'll close this PR in 10 days.

            Thanks for being a part of the Clerk community! ğŸ™
          close-issue-message: |
            Hello again ğŸ‘‹

            After 40 days of no activity, we'll close this issue. Keep in mind, I'm just a robot, so if I've closed this issue in error, please reply here and my human colleagues will reopen it.

            As a friendly reminder: The best way to see an issue fixed is to open a pull request. If you're not sure how to do that, please check out our [contributing guide](https://github.com/clerk/javascript/blob/main/docs/CONTRIBUTING.md).

            Thanks for being a part of the Clerk community! ğŸ™
          close-pr-message: |
            Hello again ğŸ‘‹

            After 60 days of no activity, we'll close this PR. Keep in mind, I'm just a robot, so if I've closed this PR in error, please reply here and my human colleagues will reopen it.

            Thanks for being a part of the Clerk community! ğŸ™
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.CLERK_COOKIE_PAT }}
          issue-inactive-days: '365'
          pr-inactive-days: '365'
          issue-comment: 'This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.'
          pr-comment: 'This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.'
          log-output: true
