name: Staging release
run-name: Staging release from ${{ github.ref_name }}

on:
  push:
    branches:
      - release/v4

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  staging-release:
    if: ${{ github.repository == 'clerk/javascript' }}
    runs-on: ${{ vars.RUNNER_LARGE }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Version packages for staging
        id: version-packages
        run: npm run version:staging | tail -1 >> "$GITHUB_OUTPUT"

      - name: Staging release
        if: steps.version-packages.outputs.success == '1'
        run: npm run release:staging
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Trigger workflows on related repos
        uses: actions/github-script@v6
        with:
          result-encoding: string
          retries: 3
          retry-exempt-status-codes: 400,401
          github-token: ${{ secrets.CLERK_COOKIE_PAT }}
          script: |
            const clerkjsVersion = require('./packages/clerk-js/package.json').version;
            const nextjsVersion = require('./packages/nextjs/package.json').version;

            if (clerkjsVersion.includes('staging')) {
              console.log('clerk-js changed, will notify clerk/cloudflare-workers');
              github.rest.actions.createWorkflowDispatch({
                owner: 'clerk',
                repo: 'cloudflare-workers',
                workflow_id: 'release-staging-clerkjs-proxy.yml',
                ref: 'main',
                inputs: { version: clerkjsVersion }
              })
            }

            if (nextjsVersion.includes('staging')) {
              console.log('clerk/nextjs changed, will notify clerk/accounts');
              github.rest.actions.createWorkflowDispatch({
                owner: 'clerk',
                repo: 'accounts',
                workflow_id: 'release-staging.yml',
                ref: 'main',
                inputs: { version: nextjsVersion }
              })
            }
